services:
  db:
    image: postgres:16-alpine
    container_name: aicron_leads_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aicron_leads_db
    volumes:
      - db_data:/var/lib/postgresql/data

  aicron:
    build: .
    container_name: aicron_app
    ports:
      - "5000:5000"

    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/aicron_leads_db?sslmode=disable

volumes:
  db_data:
